import type { NextPage } from 'next'
import Head from 'next/head'
import { Layout } from '../components/layout/Layout'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout title="Home Page">
        <p>Conteúdo da Home Page</p>
      </Layout>
      
    </div>
  )
}

export default Home
